// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package vi.practice.customer.contract.services.protobuf.customer.model;

public final class CustomerProto {
  private CustomerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HomesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .model.Home home = 1;
    java.util.List<CustomerProto.Home>
        getHomeList();
    CustomerProto.Home getHome(int index);
    int getHomeCount();
    java.util.List<? extends CustomerProto.HomeOrBuilder>
        getHomeOrBuilderList();
    CustomerProto.HomeOrBuilder getHomeOrBuilder(
        int index);
  }
  public static final class Homes extends
      com.google.protobuf.GeneratedMessage
      implements HomesOrBuilder {
    // Use Homes.newBuilder() to construct.
    private Homes(Builder builder) {
      super(builder);
    }
    private Homes(boolean noInit) {}
    
    private static final Homes defaultInstance;
    public static Homes getDefaultInstance() {
      return defaultInstance;
    }
    
    public Homes getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomerProto.internal_static_model_Homes_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomerProto.internal_static_model_Homes_fieldAccessorTable;
    }
    
    // repeated .model.Home home = 1;
    public static final int HOME_FIELD_NUMBER = 1;
    private java.util.List<CustomerProto.Home> home_;
    public java.util.List<CustomerProto.Home> getHomeList() {
      return home_;
    }
    public java.util.List<? extends CustomerProto.HomeOrBuilder>
        getHomeOrBuilderList() {
      return home_;
    }
    public int getHomeCount() {
      return home_.size();
    }
    public CustomerProto.Home getHome(int index) {
      return home_.get(index);
    }
    public CustomerProto.HomeOrBuilder getHomeOrBuilder(
        int index) {
      return home_.get(index);
    }
    
    private void initFields() {
      home_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getHomeCount(); i++) {
        if (!getHome(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < home_.size(); i++) {
        output.writeMessage(1, home_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < home_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, home_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static CustomerProto.Homes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CustomerProto.Homes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CustomerProto.Homes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CustomerProto.Homes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CustomerProto.Homes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CustomerProto.Homes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static CustomerProto.Homes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CustomerProto.Homes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CustomerProto.Homes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CustomerProto.Homes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CustomerProto.Homes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CustomerProto.HomesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomerProto.internal_static_model_Homes_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomerProto.internal_static_model_Homes_fieldAccessorTable;
      }
      
      // Construct using CustomerProto.Homes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHomeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (homeBuilder_ == null) {
          home_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          homeBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomerProto.Homes.getDescriptor();
      }
      
      public CustomerProto.Homes getDefaultInstanceForType() {
        return CustomerProto.Homes.getDefaultInstance();
      }
      
      public CustomerProto.Homes build() {
        CustomerProto.Homes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private CustomerProto.Homes buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        CustomerProto.Homes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public CustomerProto.Homes buildPartial() {
        CustomerProto.Homes result = new CustomerProto.Homes(this);
        int from_bitField0_ = bitField0_;
        if (homeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            home_ = java.util.Collections.unmodifiableList(home_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.home_ = home_;
        } else {
          result.home_ = homeBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CustomerProto.Homes) {
          return mergeFrom((CustomerProto.Homes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(CustomerProto.Homes other) {
        if (other == CustomerProto.Homes.getDefaultInstance()) return this;
        if (homeBuilder_ == null) {
          if (!other.home_.isEmpty()) {
            if (home_.isEmpty()) {
              home_ = other.home_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHomeIsMutable();
              home_.addAll(other.home_);
            }
            onChanged();
          }
        } else {
          if (!other.home_.isEmpty()) {
            if (homeBuilder_.isEmpty()) {
              homeBuilder_.dispose();
              homeBuilder_ = null;
              home_ = other.home_;
              bitField0_ = (bitField0_ & ~0x00000001);
              homeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHomeFieldBuilder() : null;
            } else {
              homeBuilder_.addAllMessages(other.home_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getHomeCount(); i++) {
          if (!getHome(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              CustomerProto.Home.Builder subBuilder = CustomerProto.Home.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addHome(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .model.Home home = 1;
      private java.util.List<CustomerProto.Home> home_ =
        java.util.Collections.emptyList();
      private void ensureHomeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          home_ = new java.util.ArrayList<CustomerProto.Home>(home_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          CustomerProto.Home, CustomerProto.Home.Builder, CustomerProto.HomeOrBuilder> homeBuilder_;
      
      public java.util.List<CustomerProto.Home> getHomeList() {
        if (homeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(home_);
        } else {
          return homeBuilder_.getMessageList();
        }
      }
      public int getHomeCount() {
        if (homeBuilder_ == null) {
          return home_.size();
        } else {
          return homeBuilder_.getCount();
        }
      }
      public CustomerProto.Home getHome(int index) {
        if (homeBuilder_ == null) {
          return home_.get(index);
        } else {
          return homeBuilder_.getMessage(index);
        }
      }
      public Builder setHome(
          int index, CustomerProto.Home value) {
        if (homeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHomeIsMutable();
          home_.set(index, value);
          onChanged();
        } else {
          homeBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setHome(
          int index, CustomerProto.Home.Builder builderForValue) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          home_.set(index, builderForValue.build());
          onChanged();
        } else {
          homeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addHome(CustomerProto.Home value) {
        if (homeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHomeIsMutable();
          home_.add(value);
          onChanged();
        } else {
          homeBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addHome(
          int index, CustomerProto.Home value) {
        if (homeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHomeIsMutable();
          home_.add(index, value);
          onChanged();
        } else {
          homeBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addHome(
          CustomerProto.Home.Builder builderForValue) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          home_.add(builderForValue.build());
          onChanged();
        } else {
          homeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addHome(
          int index, CustomerProto.Home.Builder builderForValue) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          home_.add(index, builderForValue.build());
          onChanged();
        } else {
          homeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllHome(
          java.lang.Iterable<? extends CustomerProto.Home> values) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          super.addAll(values, home_);
          onChanged();
        } else {
          homeBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearHome() {
        if (homeBuilder_ == null) {
          home_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          homeBuilder_.clear();
        }
        return this;
      }
      public Builder removeHome(int index) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          home_.remove(index);
          onChanged();
        } else {
          homeBuilder_.remove(index);
        }
        return this;
      }
      public CustomerProto.Home.Builder getHomeBuilder(
          int index) {
        return getHomeFieldBuilder().getBuilder(index);
      }
      public CustomerProto.HomeOrBuilder getHomeOrBuilder(
          int index) {
        if (homeBuilder_ == null) {
          return home_.get(index);  } else {
          return homeBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends CustomerProto.HomeOrBuilder>
           getHomeOrBuilderList() {
        if (homeBuilder_ != null) {
          return homeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(home_);
        }
      }
      public CustomerProto.Home.Builder addHomeBuilder() {
        return getHomeFieldBuilder().addBuilder(
            CustomerProto.Home.getDefaultInstance());
      }
      public CustomerProto.Home.Builder addHomeBuilder(
          int index) {
        return getHomeFieldBuilder().addBuilder(
            index, CustomerProto.Home.getDefaultInstance());
      }
      public java.util.List<CustomerProto.Home.Builder>
           getHomeBuilderList() {
        return getHomeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          CustomerProto.Home, CustomerProto.Home.Builder, CustomerProto.HomeOrBuilder>
          getHomeFieldBuilder() {
        if (homeBuilder_ == null) {
          homeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              CustomerProto.Home, CustomerProto.Home.Builder, CustomerProto.HomeOrBuilder>(
                  home_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          home_ = null;
        }
        return homeBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:model.Homes)
    }
    
    static {
      defaultInstance = new Homes(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:model.Homes)
  }
  
  public interface HomeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required string rooms = 2;
    boolean hasRooms();
    String getRooms();
    
    // optional int32 owner_id = 3;
    boolean hasOwnerId();
    int getOwnerId();
  }
  public static final class Home extends
      com.google.protobuf.GeneratedMessage
      implements HomeOrBuilder {
    // Use Home.newBuilder() to construct.
    private Home(Builder builder) {
      super(builder);
    }
    private Home(boolean noInit) {}
    
    private static final Home defaultInstance;
    public static Home getDefaultInstance() {
      return defaultInstance;
    }
    
    public Home getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomerProto.internal_static_model_Home_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomerProto.internal_static_model_Home_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required string rooms = 2;
    public static final int ROOMS_FIELD_NUMBER = 2;
    private java.lang.Object rooms_;
    public boolean hasRooms() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getRooms() {
      java.lang.Object ref = rooms_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          rooms_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRoomsBytes() {
      java.lang.Object ref = rooms_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        rooms_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 owner_id = 3;
    public static final int OWNER_ID_FIELD_NUMBER = 3;
    private int ownerId_;
    public boolean hasOwnerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getOwnerId() {
      return ownerId_;
    }
    
    private void initFields() {
      id_ = 0;
      rooms_ = "";
      ownerId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRooms()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRoomsBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, ownerId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRoomsBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ownerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static CustomerProto.Home parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CustomerProto.Home parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CustomerProto.Home parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CustomerProto.Home parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CustomerProto.Home parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CustomerProto.Home parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static CustomerProto.Home parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CustomerProto.Home parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CustomerProto.Home parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CustomerProto.Home parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CustomerProto.Home prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CustomerProto.HomeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomerProto.internal_static_model_Home_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomerProto.internal_static_model_Home_fieldAccessorTable;
      }
      
      // Construct using CustomerProto.Home.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        rooms_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ownerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomerProto.Home.getDescriptor();
      }
      
      public CustomerProto.Home getDefaultInstanceForType() {
        return CustomerProto.Home.getDefaultInstance();
      }
      
      public CustomerProto.Home build() {
        CustomerProto.Home result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private CustomerProto.Home buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        CustomerProto.Home result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public CustomerProto.Home buildPartial() {
        CustomerProto.Home result = new CustomerProto.Home(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rooms_ = rooms_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ownerId_ = ownerId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CustomerProto.Home) {
          return mergeFrom((CustomerProto.Home)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(CustomerProto.Home other) {
        if (other == CustomerProto.Home.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasRooms()) {
          setRooms(other.getRooms());
        }
        if (other.hasOwnerId()) {
          setOwnerId(other.getOwnerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasRooms()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              rooms_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              ownerId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required string rooms = 2;
      private java.lang.Object rooms_ = "";
      public boolean hasRooms() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getRooms() {
        java.lang.Object ref = rooms_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          rooms_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRooms(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rooms_ = value;
        onChanged();
        return this;
      }
      public Builder clearRooms() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rooms_ = getDefaultInstance().getRooms();
        onChanged();
        return this;
      }
      void setRooms(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        rooms_ = value;
        onChanged();
      }
      
      // optional int32 owner_id = 3;
      private int ownerId_ ;
      public boolean hasOwnerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getOwnerId() {
        return ownerId_;
      }
      public Builder setOwnerId(int value) {
        bitField0_ |= 0x00000004;
        ownerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearOwnerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ownerId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:model.Home)
    }
    
    static {
      defaultInstance = new Home(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:model.Home)
  }
  
  public interface CustomersOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .model.Customer customers = 1;
    java.util.List<CustomerProto.Customer>
        getCustomersList();
    CustomerProto.Customer getCustomers(int index);
    int getCustomersCount();
    java.util.List<? extends CustomerProto.CustomerOrBuilder>
        getCustomersOrBuilderList();
    CustomerProto.CustomerOrBuilder getCustomersOrBuilder(
        int index);
  }
  public static final class Customers extends
      com.google.protobuf.GeneratedMessage
      implements CustomersOrBuilder {
    // Use Customers.newBuilder() to construct.
    private Customers(Builder builder) {
      super(builder);
    }
    private Customers(boolean noInit) {}
    
    private static final Customers defaultInstance;
    public static Customers getDefaultInstance() {
      return defaultInstance;
    }
    
    public Customers getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomerProto.internal_static_model_Customers_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomerProto.internal_static_model_Customers_fieldAccessorTable;
    }
    
    // repeated .model.Customer customers = 1;
    public static final int CUSTOMERS_FIELD_NUMBER = 1;
    private java.util.List<CustomerProto.Customer> customers_;
    public java.util.List<CustomerProto.Customer> getCustomersList() {
      return customers_;
    }
    public java.util.List<? extends CustomerProto.CustomerOrBuilder>
        getCustomersOrBuilderList() {
      return customers_;
    }
    public int getCustomersCount() {
      return customers_.size();
    }
    public CustomerProto.Customer getCustomers(int index) {
      return customers_.get(index);
    }
    public CustomerProto.CustomerOrBuilder getCustomersOrBuilder(
        int index) {
      return customers_.get(index);
    }
    
    private void initFields() {
      customers_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getCustomersCount(); i++) {
        if (!getCustomers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < customers_.size(); i++) {
        output.writeMessage(1, customers_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < customers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, customers_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static CustomerProto.Customers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CustomerProto.Customers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CustomerProto.Customers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CustomerProto.Customers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CustomerProto.Customers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CustomerProto.Customers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static CustomerProto.Customers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CustomerProto.Customers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CustomerProto.Customers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CustomerProto.Customers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CustomerProto.Customers prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CustomerProto.CustomersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomerProto.internal_static_model_Customers_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomerProto.internal_static_model_Customers_fieldAccessorTable;
      }
      
      // Construct using CustomerProto.Customers.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCustomersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (customersBuilder_ == null) {
          customers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          customersBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomerProto.Customers.getDescriptor();
      }
      
      public CustomerProto.Customers getDefaultInstanceForType() {
        return CustomerProto.Customers.getDefaultInstance();
      }
      
      public CustomerProto.Customers build() {
        CustomerProto.Customers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private CustomerProto.Customers buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        CustomerProto.Customers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public CustomerProto.Customers buildPartial() {
        CustomerProto.Customers result = new CustomerProto.Customers(this);
        int from_bitField0_ = bitField0_;
        if (customersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            customers_ = java.util.Collections.unmodifiableList(customers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.customers_ = customers_;
        } else {
          result.customers_ = customersBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CustomerProto.Customers) {
          return mergeFrom((CustomerProto.Customers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(CustomerProto.Customers other) {
        if (other == CustomerProto.Customers.getDefaultInstance()) return this;
        if (customersBuilder_ == null) {
          if (!other.customers_.isEmpty()) {
            if (customers_.isEmpty()) {
              customers_ = other.customers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCustomersIsMutable();
              customers_.addAll(other.customers_);
            }
            onChanged();
          }
        } else {
          if (!other.customers_.isEmpty()) {
            if (customersBuilder_.isEmpty()) {
              customersBuilder_.dispose();
              customersBuilder_ = null;
              customers_ = other.customers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              customersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCustomersFieldBuilder() : null;
            } else {
              customersBuilder_.addAllMessages(other.customers_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getCustomersCount(); i++) {
          if (!getCustomers(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              CustomerProto.Customer.Builder subBuilder = CustomerProto.Customer.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addCustomers(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .model.Customer customers = 1;
      private java.util.List<CustomerProto.Customer> customers_ =
        java.util.Collections.emptyList();
      private void ensureCustomersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          customers_ = new java.util.ArrayList<CustomerProto.Customer>(customers_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          CustomerProto.Customer, CustomerProto.Customer.Builder, CustomerProto.CustomerOrBuilder> customersBuilder_;
      
      public java.util.List<CustomerProto.Customer> getCustomersList() {
        if (customersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(customers_);
        } else {
          return customersBuilder_.getMessageList();
        }
      }
      public int getCustomersCount() {
        if (customersBuilder_ == null) {
          return customers_.size();
        } else {
          return customersBuilder_.getCount();
        }
      }
      public CustomerProto.Customer getCustomers(int index) {
        if (customersBuilder_ == null) {
          return customers_.get(index);
        } else {
          return customersBuilder_.getMessage(index);
        }
      }
      public Builder setCustomers(
          int index, CustomerProto.Customer value) {
        if (customersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomersIsMutable();
          customers_.set(index, value);
          onChanged();
        } else {
          customersBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setCustomers(
          int index, CustomerProto.Customer.Builder builderForValue) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          customers_.set(index, builderForValue.build());
          onChanged();
        } else {
          customersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addCustomers(CustomerProto.Customer value) {
        if (customersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomersIsMutable();
          customers_.add(value);
          onChanged();
        } else {
          customersBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addCustomers(
          int index, CustomerProto.Customer value) {
        if (customersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomersIsMutable();
          customers_.add(index, value);
          onChanged();
        } else {
          customersBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addCustomers(
          CustomerProto.Customer.Builder builderForValue) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          customers_.add(builderForValue.build());
          onChanged();
        } else {
          customersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addCustomers(
          int index, CustomerProto.Customer.Builder builderForValue) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          customers_.add(index, builderForValue.build());
          onChanged();
        } else {
          customersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllCustomers(
          java.lang.Iterable<? extends CustomerProto.Customer> values) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          super.addAll(values, customers_);
          onChanged();
        } else {
          customersBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearCustomers() {
        if (customersBuilder_ == null) {
          customers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          customersBuilder_.clear();
        }
        return this;
      }
      public Builder removeCustomers(int index) {
        if (customersBuilder_ == null) {
          ensureCustomersIsMutable();
          customers_.remove(index);
          onChanged();
        } else {
          customersBuilder_.remove(index);
        }
        return this;
      }
      public CustomerProto.Customer.Builder getCustomersBuilder(
          int index) {
        return getCustomersFieldBuilder().getBuilder(index);
      }
      public CustomerProto.CustomerOrBuilder getCustomersOrBuilder(
          int index) {
        if (customersBuilder_ == null) {
          return customers_.get(index);  } else {
          return customersBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends CustomerProto.CustomerOrBuilder>
           getCustomersOrBuilderList() {
        if (customersBuilder_ != null) {
          return customersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(customers_);
        }
      }
      public CustomerProto.Customer.Builder addCustomersBuilder() {
        return getCustomersFieldBuilder().addBuilder(
            CustomerProto.Customer.getDefaultInstance());
      }
      public CustomerProto.Customer.Builder addCustomersBuilder(
          int index) {
        return getCustomersFieldBuilder().addBuilder(
            index, CustomerProto.Customer.getDefaultInstance());
      }
      public java.util.List<CustomerProto.Customer.Builder>
           getCustomersBuilderList() {
        return getCustomersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          CustomerProto.Customer, CustomerProto.Customer.Builder, CustomerProto.CustomerOrBuilder>
          getCustomersFieldBuilder() {
        if (customersBuilder_ == null) {
          customersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              CustomerProto.Customer, CustomerProto.Customer.Builder, CustomerProto.CustomerOrBuilder>(
                  customers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          customers_ = null;
        }
        return customersBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:model.Customers)
    }
    
    static {
      defaultInstance = new Customers(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:model.Customers)
  }
  
  public interface CustomerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required string aadhar = 2;
    boolean hasAadhar();
    String getAadhar();
    
    // optional string name = 3;
    boolean hasName();
    String getName();
    
    // required .model.Customer.CustomerType type = 4;
    boolean hasType();
    CustomerProto.Customer.CustomerType getType();
    
    // repeated .model.Home homes = 5;
    java.util.List<CustomerProto.Home>
        getHomesList();
    CustomerProto.Home getHomes(int index);
    int getHomesCount();
    java.util.List<? extends CustomerProto.HomeOrBuilder>
        getHomesOrBuilderList();
    CustomerProto.HomeOrBuilder getHomesOrBuilder(
        int index);
  }
  public static final class Customer extends
      com.google.protobuf.GeneratedMessage
      implements CustomerOrBuilder {
    // Use Customer.newBuilder() to construct.
    private Customer(Builder builder) {
      super(builder);
    }
    private Customer(boolean noInit) {}
    
    private static final Customer defaultInstance;
    public static Customer getDefaultInstance() {
      return defaultInstance;
    }
    
    public Customer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomerProto.internal_static_model_Customer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomerProto.internal_static_model_Customer_fieldAccessorTable;
    }
    
    public enum CustomerType
        implements com.google.protobuf.ProtocolMessageEnum {
      INDIVIDUAL(0, 0),
      COMPANY(1, 1),
      ;
      
      public static final int INDIVIDUAL_VALUE = 0;
      public static final int COMPANY_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static CustomerType valueOf(int value) {
        switch (value) {
          case 0: return INDIVIDUAL;
          case 1: return COMPANY;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CustomerType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CustomerType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CustomerType>() {
              public CustomerType findValueByNumber(int number) {
                return CustomerType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return CustomerProto.Customer.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final CustomerType[] VALUES = {
        INDIVIDUAL, COMPANY, 
      };
      
      public static CustomerType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private CustomerType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:model.Customer.CustomerType)
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required string aadhar = 2;
    public static final int AADHAR_FIELD_NUMBER = 2;
    private java.lang.Object aadhar_;
    public boolean hasAadhar() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getAadhar() {
      java.lang.Object ref = aadhar_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          aadhar_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAadharBytes() {
      java.lang.Object ref = aadhar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        aadhar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .model.Customer.CustomerType type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private CustomerProto.Customer.CustomerType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public CustomerProto.Customer.CustomerType getType() {
      return type_;
    }
    
    // repeated .model.Home homes = 5;
    public static final int HOMES_FIELD_NUMBER = 5;
    private java.util.List<CustomerProto.Home> homes_;
    public java.util.List<CustomerProto.Home> getHomesList() {
      return homes_;
    }
    public java.util.List<? extends CustomerProto.HomeOrBuilder>
        getHomesOrBuilderList() {
      return homes_;
    }
    public int getHomesCount() {
      return homes_.size();
    }
    public CustomerProto.Home getHomes(int index) {
      return homes_.get(index);
    }
    public CustomerProto.HomeOrBuilder getHomesOrBuilder(
        int index) {
      return homes_.get(index);
    }
    
    private void initFields() {
      id_ = 0;
      aadhar_ = "";
      name_ = "";
      type_ = CustomerProto.Customer.CustomerType.INDIVIDUAL;
      homes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAadhar()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getHomesCount(); i++) {
        if (!getHomes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAadharBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, type_.getNumber());
      }
      for (int i = 0; i < homes_.size(); i++) {
        output.writeMessage(5, homes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAadharBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_.getNumber());
      }
      for (int i = 0; i < homes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, homes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static CustomerProto.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CustomerProto.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CustomerProto.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CustomerProto.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CustomerProto.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CustomerProto.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static CustomerProto.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CustomerProto.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CustomerProto.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CustomerProto.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CustomerProto.Customer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CustomerProto.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomerProto.internal_static_model_Customer_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomerProto.internal_static_model_Customer_fieldAccessorTable;
      }
      
      // Construct using CustomerProto.Customer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHomesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        aadhar_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = CustomerProto.Customer.CustomerType.INDIVIDUAL;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (homesBuilder_ == null) {
          homes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          homesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomerProto.Customer.getDescriptor();
      }
      
      public CustomerProto.Customer getDefaultInstanceForType() {
        return CustomerProto.Customer.getDefaultInstance();
      }
      
      public CustomerProto.Customer build() {
        CustomerProto.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private CustomerProto.Customer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        CustomerProto.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public CustomerProto.Customer buildPartial() {
        CustomerProto.Customer result = new CustomerProto.Customer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.aadhar_ = aadhar_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (homesBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            homes_ = java.util.Collections.unmodifiableList(homes_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.homes_ = homes_;
        } else {
          result.homes_ = homesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CustomerProto.Customer) {
          return mergeFrom((CustomerProto.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(CustomerProto.Customer other) {
        if (other == CustomerProto.Customer.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAadhar()) {
          setAadhar(other.getAadhar());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (homesBuilder_ == null) {
          if (!other.homes_.isEmpty()) {
            if (homes_.isEmpty()) {
              homes_ = other.homes_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureHomesIsMutable();
              homes_.addAll(other.homes_);
            }
            onChanged();
          }
        } else {
          if (!other.homes_.isEmpty()) {
            if (homesBuilder_.isEmpty()) {
              homesBuilder_.dispose();
              homesBuilder_ = null;
              homes_ = other.homes_;
              bitField0_ = (bitField0_ & ~0x00000010);
              homesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHomesFieldBuilder() : null;
            } else {
              homesBuilder_.addAllMessages(other.homes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasAadhar()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        for (int i = 0; i < getHomesCount(); i++) {
          if (!getHomes(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              aadhar_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              CustomerProto.Customer.CustomerType value = CustomerProto.Customer.CustomerType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                type_ = value;
              }
              break;
            }
            case 42: {
              CustomerProto.Home.Builder subBuilder = CustomerProto.Home.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addHomes(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required string aadhar = 2;
      private java.lang.Object aadhar_ = "";
      public boolean hasAadhar() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAadhar() {
        java.lang.Object ref = aadhar_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          aadhar_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAadhar(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        aadhar_ = value;
        onChanged();
        return this;
      }
      public Builder clearAadhar() {
        bitField0_ = (bitField0_ & ~0x00000002);
        aadhar_ = getDefaultInstance().getAadhar();
        onChanged();
        return this;
      }
      void setAadhar(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        aadhar_ = value;
        onChanged();
      }
      
      // optional string name = 3;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
      }
      
      // required .model.Customer.CustomerType type = 4;
      private CustomerProto.Customer.CustomerType type_ = CustomerProto.Customer.CustomerType.INDIVIDUAL;
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public CustomerProto.Customer.CustomerType getType() {
        return type_;
      }
      public Builder setType(CustomerProto.Customer.CustomerType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = CustomerProto.Customer.CustomerType.INDIVIDUAL;
        onChanged();
        return this;
      }
      
      // repeated .model.Home homes = 5;
      private java.util.List<CustomerProto.Home> homes_ =
        java.util.Collections.emptyList();
      private void ensureHomesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          homes_ = new java.util.ArrayList<CustomerProto.Home>(homes_);
          bitField0_ |= 0x00000010;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          CustomerProto.Home, CustomerProto.Home.Builder, CustomerProto.HomeOrBuilder> homesBuilder_;
      
      public java.util.List<CustomerProto.Home> getHomesList() {
        if (homesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(homes_);
        } else {
          return homesBuilder_.getMessageList();
        }
      }
      public int getHomesCount() {
        if (homesBuilder_ == null) {
          return homes_.size();
        } else {
          return homesBuilder_.getCount();
        }
      }
      public CustomerProto.Home getHomes(int index) {
        if (homesBuilder_ == null) {
          return homes_.get(index);
        } else {
          return homesBuilder_.getMessage(index);
        }
      }
      public Builder setHomes(
          int index, CustomerProto.Home value) {
        if (homesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHomesIsMutable();
          homes_.set(index, value);
          onChanged();
        } else {
          homesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setHomes(
          int index, CustomerProto.Home.Builder builderForValue) {
        if (homesBuilder_ == null) {
          ensureHomesIsMutable();
          homes_.set(index, builderForValue.build());
          onChanged();
        } else {
          homesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addHomes(CustomerProto.Home value) {
        if (homesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHomesIsMutable();
          homes_.add(value);
          onChanged();
        } else {
          homesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addHomes(
          int index, CustomerProto.Home value) {
        if (homesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHomesIsMutable();
          homes_.add(index, value);
          onChanged();
        } else {
          homesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addHomes(
          CustomerProto.Home.Builder builderForValue) {
        if (homesBuilder_ == null) {
          ensureHomesIsMutable();
          homes_.add(builderForValue.build());
          onChanged();
        } else {
          homesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addHomes(
          int index, CustomerProto.Home.Builder builderForValue) {
        if (homesBuilder_ == null) {
          ensureHomesIsMutable();
          homes_.add(index, builderForValue.build());
          onChanged();
        } else {
          homesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllHomes(
          java.lang.Iterable<? extends CustomerProto.Home> values) {
        if (homesBuilder_ == null) {
          ensureHomesIsMutable();
          super.addAll(values, homes_);
          onChanged();
        } else {
          homesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearHomes() {
        if (homesBuilder_ == null) {
          homes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          homesBuilder_.clear();
        }
        return this;
      }
      public Builder removeHomes(int index) {
        if (homesBuilder_ == null) {
          ensureHomesIsMutable();
          homes_.remove(index);
          onChanged();
        } else {
          homesBuilder_.remove(index);
        }
        return this;
      }
      public CustomerProto.Home.Builder getHomesBuilder(
          int index) {
        return getHomesFieldBuilder().getBuilder(index);
      }
      public CustomerProto.HomeOrBuilder getHomesOrBuilder(
          int index) {
        if (homesBuilder_ == null) {
          return homes_.get(index);  } else {
          return homesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends CustomerProto.HomeOrBuilder>
           getHomesOrBuilderList() {
        if (homesBuilder_ != null) {
          return homesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(homes_);
        }
      }
      public CustomerProto.Home.Builder addHomesBuilder() {
        return getHomesFieldBuilder().addBuilder(
            CustomerProto.Home.getDefaultInstance());
      }
      public CustomerProto.Home.Builder addHomesBuilder(
          int index) {
        return getHomesFieldBuilder().addBuilder(
            index, CustomerProto.Home.getDefaultInstance());
      }
      public java.util.List<CustomerProto.Home.Builder>
           getHomesBuilderList() {
        return getHomesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          CustomerProto.Home, CustomerProto.Home.Builder, CustomerProto.HomeOrBuilder>
          getHomesFieldBuilder() {
        if (homesBuilder_ == null) {
          homesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              CustomerProto.Home, CustomerProto.Home.Builder, CustomerProto.HomeOrBuilder>(
                  homes_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          homes_ = null;
        }
        return homesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:model.Customer)
    }
    
    static {
      defaultInstance = new Customer(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:model.Customer)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Homes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_Homes_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Home_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_Home_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Customers_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_Customers_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Customer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_Customer_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\022\005model\"\"\n\005Homes\022\031\n\004home" +
      "\030\001 \003(\0132\013.model.Home\"3\n\004Home\022\n\n\002id\030\001 \002(\005\022" +
      "\r\n\005rooms\030\002 \002(\t\022\020\n\010owner_id\030\003 \001(\005\"/\n\tCust" +
      "omers\022\"\n\tcustomers\030\001 \003(\0132\017.model.Custome" +
      "r\"\251\001\n\010Customer\022\n\n\002id\030\001 \002(\005\022\016\n\006aadhar\030\002 \002" +
      "(\t\022\014\n\004name\030\003 \001(\t\022*\n\004type\030\004 \002(\0162\034.model.C" +
      "ustomer.CustomerType\022\032\n\005homes\030\005 \003(\0132\013.mo" +
      "del.Home\"+\n\014CustomerType\022\016\n\nINDIVIDUAL\020\000" +
      "\022\013\n\007COMPANY\020\001B=\n,vi.practice.services.pr" +
      "otobuf.customer.modelB\rCustomerProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_model_Homes_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_model_Homes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_model_Homes_descriptor,
              new java.lang.String[] { "Home", },
              CustomerProto.Homes.class,
              CustomerProto.Homes.Builder.class);
          internal_static_model_Home_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_model_Home_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_model_Home_descriptor,
              new java.lang.String[] { "Id", "Rooms", "OwnerId", },
              CustomerProto.Home.class,
              CustomerProto.Home.Builder.class);
          internal_static_model_Customers_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_model_Customers_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_model_Customers_descriptor,
              new java.lang.String[] { "Customers", },
              CustomerProto.Customers.class,
              CustomerProto.Customers.Builder.class);
          internal_static_model_Customer_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_model_Customer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_model_Customer_descriptor,
              new java.lang.String[] { "Id", "Aadhar", "Name", "Type", "Homes", },
              CustomerProto.Customer.class,
              CustomerProto.Customer.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
