// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: home.proto

package protobuf.home.model;

public final class HomeProto {
  private HomeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HomesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.Homes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .model.Home home = 1;</code>
     */
    java.util.List<HomeProto.Home>
        getHomeList();
    /**
     * <code>repeated .model.Home home = 1;</code>
     */
    HomeProto.Home getHome(int index);
    /**
     * <code>repeated .model.Home home = 1;</code>
     */
    int getHomeCount();
    /**
     * <code>repeated .model.Home home = 1;</code>
     */
    java.util.List<? extends HomeProto.HomeOrBuilder>
        getHomeOrBuilderList();
    /**
     * <code>repeated .model.Home home = 1;</code>
     */
    HomeProto.HomeOrBuilder getHomeOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code model.Homes}
   */
  public  static final class Homes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.Homes)
      HomesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Homes.newBuilder() to construct.
    private Homes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Homes() {
      home_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Homes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                home_ = new java.util.ArrayList<HomeProto.Home>();
                mutable_bitField0_ |= 0x00000001;
              }
              home_.add(
                  input.readMessage(HomeProto.Home.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          home_ = java.util.Collections.unmodifiableList(home_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HomeProto.internal_static_model_Homes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HomeProto.internal_static_model_Homes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HomeProto.Homes.class, HomeProto.Homes.Builder.class);
    }

    public static final int HOME_FIELD_NUMBER = 1;
    private java.util.List<HomeProto.Home> home_;
    /**
     * <code>repeated .model.Home home = 1;</code>
     */
    public java.util.List<HomeProto.Home> getHomeList() {
      return home_;
    }
    /**
     * <code>repeated .model.Home home = 1;</code>
     */
    public java.util.List<? extends HomeProto.HomeOrBuilder>
        getHomeOrBuilderList() {
      return home_;
    }
    /**
     * <code>repeated .model.Home home = 1;</code>
     */
    public int getHomeCount() {
      return home_.size();
    }
    /**
     * <code>repeated .model.Home home = 1;</code>
     */
    public HomeProto.Home getHome(int index) {
      return home_.get(index);
    }
    /**
     * <code>repeated .model.Home home = 1;</code>
     */
    public HomeProto.HomeOrBuilder getHomeOrBuilder(
        int index) {
      return home_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getHomeCount(); i++) {
        if (!getHome(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < home_.size(); i++) {
        output.writeMessage(1, home_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < home_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, home_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HomeProto.Homes)) {
        return super.equals(obj);
      }
      HomeProto.Homes other = (HomeProto.Homes) obj;

      if (!getHomeList()
          .equals(other.getHomeList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getHomeCount() > 0) {
        hash = (37 * hash) + HOME_FIELD_NUMBER;
        hash = (53 * hash) + getHomeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HomeProto.Homes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HomeProto.Homes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HomeProto.Homes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HomeProto.Homes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HomeProto.Homes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HomeProto.Homes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HomeProto.Homes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HomeProto.Homes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HomeProto.Homes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HomeProto.Homes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HomeProto.Homes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HomeProto.Homes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HomeProto.Homes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.Homes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.Homes)
        HomeProto.HomesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HomeProto.internal_static_model_Homes_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HomeProto.internal_static_model_Homes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HomeProto.Homes.class, HomeProto.Homes.Builder.class);
      }

      // Construct using vi.practice.services.protobuf.home.model.HomeProto.Homes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHomeFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (homeBuilder_ == null) {
          home_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          homeBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HomeProto.internal_static_model_Homes_descriptor;
      }

      @Override
      public HomeProto.Homes getDefaultInstanceForType() {
        return HomeProto.Homes.getDefaultInstance();
      }

      @Override
      public HomeProto.Homes build() {
        HomeProto.Homes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public HomeProto.Homes buildPartial() {
        HomeProto.Homes result = new HomeProto.Homes(this);
        int from_bitField0_ = bitField0_;
        if (homeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            home_ = java.util.Collections.unmodifiableList(home_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.home_ = home_;
        } else {
          result.home_ = homeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HomeProto.Homes) {
          return mergeFrom((HomeProto.Homes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HomeProto.Homes other) {
        if (other == HomeProto.Homes.getDefaultInstance()) return this;
        if (homeBuilder_ == null) {
          if (!other.home_.isEmpty()) {
            if (home_.isEmpty()) {
              home_ = other.home_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHomeIsMutable();
              home_.addAll(other.home_);
            }
            onChanged();
          }
        } else {
          if (!other.home_.isEmpty()) {
            if (homeBuilder_.isEmpty()) {
              homeBuilder_.dispose();
              homeBuilder_ = null;
              home_ = other.home_;
              bitField0_ = (bitField0_ & ~0x00000001);
              homeBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHomeFieldBuilder() : null;
            } else {
              homeBuilder_.addAllMessages(other.home_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        for (int i = 0; i < getHomeCount(); i++) {
          if (!getHome(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HomeProto.Homes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HomeProto.Homes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<HomeProto.Home> home_ =
        java.util.Collections.emptyList();
      private void ensureHomeIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          home_ = new java.util.ArrayList<HomeProto.Home>(home_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          HomeProto.Home, HomeProto.Home.Builder, HomeProto.HomeOrBuilder> homeBuilder_;

      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public java.util.List<HomeProto.Home> getHomeList() {
        if (homeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(home_);
        } else {
          return homeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public int getHomeCount() {
        if (homeBuilder_ == null) {
          return home_.size();
        } else {
          return homeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public HomeProto.Home getHome(int index) {
        if (homeBuilder_ == null) {
          return home_.get(index);
        } else {
          return homeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public Builder setHome(
          int index, HomeProto.Home value) {
        if (homeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHomeIsMutable();
          home_.set(index, value);
          onChanged();
        } else {
          homeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public Builder setHome(
          int index, HomeProto.Home.Builder builderForValue) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          home_.set(index, builderForValue.build());
          onChanged();
        } else {
          homeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public Builder addHome(HomeProto.Home value) {
        if (homeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHomeIsMutable();
          home_.add(value);
          onChanged();
        } else {
          homeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public Builder addHome(
          int index, HomeProto.Home value) {
        if (homeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHomeIsMutable();
          home_.add(index, value);
          onChanged();
        } else {
          homeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public Builder addHome(
          HomeProto.Home.Builder builderForValue) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          home_.add(builderForValue.build());
          onChanged();
        } else {
          homeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public Builder addHome(
          int index, HomeProto.Home.Builder builderForValue) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          home_.add(index, builderForValue.build());
          onChanged();
        } else {
          homeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public Builder addAllHome(
          Iterable<? extends HomeProto.Home> values) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, home_);
          onChanged();
        } else {
          homeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public Builder clearHome() {
        if (homeBuilder_ == null) {
          home_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          homeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public Builder removeHome(int index) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          home_.remove(index);
          onChanged();
        } else {
          homeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public HomeProto.Home.Builder getHomeBuilder(
          int index) {
        return getHomeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public HomeProto.HomeOrBuilder getHomeOrBuilder(
          int index) {
        if (homeBuilder_ == null) {
          return home_.get(index);  } else {
          return homeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public java.util.List<? extends HomeProto.HomeOrBuilder>
           getHomeOrBuilderList() {
        if (homeBuilder_ != null) {
          return homeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(home_);
        }
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public HomeProto.Home.Builder addHomeBuilder() {
        return getHomeFieldBuilder().addBuilder(
            HomeProto.Home.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public HomeProto.Home.Builder addHomeBuilder(
          int index) {
        return getHomeFieldBuilder().addBuilder(
            index, HomeProto.Home.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Home home = 1;</code>
       */
      public java.util.List<HomeProto.Home.Builder>
           getHomeBuilderList() {
        return getHomeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          HomeProto.Home, HomeProto.Home.Builder, HomeProto.HomeOrBuilder>
          getHomeFieldBuilder() {
        if (homeBuilder_ == null) {
          homeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              HomeProto.Home, HomeProto.Home.Builder, HomeProto.HomeOrBuilder>(
                  home_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          home_ = null;
        }
        return homeBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.Homes)
    }

    // @@protoc_insertion_point(class_scope:model.Homes)
    private static final HomeProto.Homes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HomeProto.Homes();
    }

    public static HomeProto.Homes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Homes>
        PARSER = new com.google.protobuf.AbstractParser<Homes>() {
      @Override
      public Homes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Homes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Homes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Homes> getParserForType() {
      return PARSER;
    }

    @Override
    public HomeProto.Homes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HomeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.Home)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string rooms = 2;</code>
     */
    boolean hasRooms();
    /**
     * <code>required string rooms = 2;</code>
     */
    String getRooms();
    /**
     * <code>required string rooms = 2;</code>
     */
    com.google.protobuf.ByteString
        getRoomsBytes();

    /**
     * <code>required int32 owner_id = 3;</code>
     */
    boolean hasOwnerId();
    /**
     * <code>required int32 owner_id = 3;</code>
     */
    int getOwnerId();
  }
  /**
   * Protobuf type {@code model.Home}
   */
  public  static final class Home extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.Home)
      HomeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Home.newBuilder() to construct.
    private Home(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Home() {
      rooms_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Home(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              rooms_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              ownerId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HomeProto.internal_static_model_Home_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HomeProto.internal_static_model_Home_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HomeProto.Home.class, HomeProto.Home.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int ROOMS_FIELD_NUMBER = 2;
    private volatile Object rooms_;
    /**
     * <code>required string rooms = 2;</code>
     */
    public boolean hasRooms() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string rooms = 2;</code>
     */
    public String getRooms() {
      Object ref = rooms_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rooms_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string rooms = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRoomsBytes() {
      Object ref = rooms_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rooms_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OWNER_ID_FIELD_NUMBER = 3;
    private int ownerId_;
    /**
     * <code>required int32 owner_id = 3;</code>
     */
    public boolean hasOwnerId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 owner_id = 3;</code>
     */
    public int getOwnerId() {
      return ownerId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRooms()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOwnerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rooms_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, ownerId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rooms_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ownerId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HomeProto.Home)) {
        return super.equals(obj);
      }
      HomeProto.Home other = (HomeProto.Home) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasRooms() != other.hasRooms()) return false;
      if (hasRooms()) {
        if (!getRooms()
            .equals(other.getRooms())) return false;
      }
      if (hasOwnerId() != other.hasOwnerId()) return false;
      if (hasOwnerId()) {
        if (getOwnerId()
            != other.getOwnerId()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasRooms()) {
        hash = (37 * hash) + ROOMS_FIELD_NUMBER;
        hash = (53 * hash) + getRooms().hashCode();
      }
      if (hasOwnerId()) {
        hash = (37 * hash) + OWNER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getOwnerId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HomeProto.Home parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HomeProto.Home parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HomeProto.Home parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HomeProto.Home parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HomeProto.Home parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HomeProto.Home parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HomeProto.Home parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HomeProto.Home parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HomeProto.Home parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HomeProto.Home parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HomeProto.Home parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HomeProto.Home parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HomeProto.Home prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.Home}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.Home)
        HomeProto.HomeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HomeProto.internal_static_model_Home_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HomeProto.internal_static_model_Home_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HomeProto.Home.class, HomeProto.Home.Builder.class);
      }

      // Construct using vi.practice.services.protobuf.home.model.HomeProto.Home.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        rooms_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ownerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HomeProto.internal_static_model_Home_descriptor;
      }

      @Override
      public HomeProto.Home getDefaultInstanceForType() {
        return HomeProto.Home.getDefaultInstance();
      }

      @Override
      public HomeProto.Home build() {
        HomeProto.Home result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public HomeProto.Home buildPartial() {
        HomeProto.Home result = new HomeProto.Home(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rooms_ = rooms_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.ownerId_ = ownerId_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HomeProto.Home) {
          return mergeFrom((HomeProto.Home)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HomeProto.Home other) {
        if (other == HomeProto.Home.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasRooms()) {
          bitField0_ |= 0x00000002;
          rooms_ = other.rooms_;
          onChanged();
        }
        if (other.hasOwnerId()) {
          setOwnerId(other.getOwnerId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasRooms()) {
          return false;
        }
        if (!hasOwnerId()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HomeProto.Home parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HomeProto.Home) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private Object rooms_ = "";
      /**
       * <code>required string rooms = 2;</code>
       */
      public boolean hasRooms() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string rooms = 2;</code>
       */
      public String getRooms() {
        Object ref = rooms_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            rooms_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string rooms = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRoomsBytes() {
        Object ref = rooms_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          rooms_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string rooms = 2;</code>
       */
      public Builder setRooms(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rooms_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string rooms = 2;</code>
       */
      public Builder clearRooms() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rooms_ = getDefaultInstance().getRooms();
        onChanged();
        return this;
      }
      /**
       * <code>required string rooms = 2;</code>
       */
      public Builder setRoomsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rooms_ = value;
        onChanged();
        return this;
      }

      private int ownerId_ ;
      /**
       * <code>required int32 owner_id = 3;</code>
       */
      public boolean hasOwnerId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 owner_id = 3;</code>
       */
      public int getOwnerId() {
        return ownerId_;
      }
      /**
       * <code>required int32 owner_id = 3;</code>
       */
      public Builder setOwnerId(int value) {
        bitField0_ |= 0x00000004;
        ownerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 owner_id = 3;</code>
       */
      public Builder clearOwnerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ownerId_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.Home)
    }

    // @@protoc_insertion_point(class_scope:model.Home)
    private static final HomeProto.Home DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HomeProto.Home();
    }

    public static HomeProto.Home getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Home>
        PARSER = new com.google.protobuf.AbstractParser<Home>() {
      @Override
      public Home parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Home(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Home> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Home> getParserForType() {
      return PARSER;
    }

    @Override
    public HomeProto.Home getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Homes_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Homes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Home_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Home_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nhome.proto\022\005model\"\"\n\005Homes\022\031\n\004home\030\001 \003" +
      "(\0132\013.model.Home\"3\n\004Home\022\n\n\002id\030\001 \002(\005\022\r\n\005r" +
      "ooms\030\002 \002(\t\022\020\n\010owner_id\030\003 \002(\005B5\n(vi.pract" +
      "ice.services.protobuf.home.modelB\tHomePr" +
      "oto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_model_Homes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_Homes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Homes_descriptor,
        new String[] { "Home", });
    internal_static_model_Home_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_Home_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Home_descriptor,
        new String[] { "Id", "Rooms", "OwnerId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
