// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: home.proto

package vi.practice.customer.contract.services.protobuf.home.model;

public final class HomeProto {
  private HomeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HomesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .model.Home home = 1;
    java.util.List<HomeProto.Home>
        getHomeList();
    HomeProto.Home getHome(int index);
    int getHomeCount();
    java.util.List<? extends HomeProto.HomeOrBuilder>
        getHomeOrBuilderList();
    HomeProto.HomeOrBuilder getHomeOrBuilder(
        int index);
  }
  public static final class Homes extends
      com.google.protobuf.GeneratedMessage
      implements HomesOrBuilder {
    // Use Homes.newBuilder() to construct.
    private Homes(Builder builder) {
      super(builder);
    }
    private Homes(boolean noInit) {}
    
    private static final Homes defaultInstance;
    public static Homes getDefaultInstance() {
      return defaultInstance;
    }
    
    public Homes getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HomeProto.internal_static_model_Homes_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HomeProto.internal_static_model_Homes_fieldAccessorTable;
    }
    
    // repeated .model.Home home = 1;
    public static final int HOME_FIELD_NUMBER = 1;
    private java.util.List<HomeProto.Home> home_;
    public java.util.List<HomeProto.Home> getHomeList() {
      return home_;
    }
    public java.util.List<? extends HomeProto.HomeOrBuilder>
        getHomeOrBuilderList() {
      return home_;
    }
    public int getHomeCount() {
      return home_.size();
    }
    public HomeProto.Home getHome(int index) {
      return home_.get(index);
    }
    public HomeProto.HomeOrBuilder getHomeOrBuilder(
        int index) {
      return home_.get(index);
    }
    
    private void initFields() {
      home_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getHomeCount(); i++) {
        if (!getHome(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < home_.size(); i++) {
        output.writeMessage(1, home_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < home_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, home_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static HomeProto.Homes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static HomeProto.Homes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static HomeProto.Homes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static HomeProto.Homes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static HomeProto.Homes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static HomeProto.Homes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static HomeProto.Homes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static HomeProto.Homes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static HomeProto.Homes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static HomeProto.Homes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HomeProto.Homes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements HomeProto.HomesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HomeProto.internal_static_model_Homes_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HomeProto.internal_static_model_Homes_fieldAccessorTable;
      }
      
      // Construct using HomeProto.Homes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHomeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (homeBuilder_ == null) {
          home_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          homeBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HomeProto.Homes.getDescriptor();
      }
      
      public HomeProto.Homes getDefaultInstanceForType() {
        return HomeProto.Homes.getDefaultInstance();
      }
      
      public HomeProto.Homes build() {
        HomeProto.Homes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private HomeProto.Homes buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        HomeProto.Homes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public HomeProto.Homes buildPartial() {
        HomeProto.Homes result = new HomeProto.Homes(this);
        int from_bitField0_ = bitField0_;
        if (homeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            home_ = java.util.Collections.unmodifiableList(home_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.home_ = home_;
        } else {
          result.home_ = homeBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HomeProto.Homes) {
          return mergeFrom((HomeProto.Homes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(HomeProto.Homes other) {
        if (other == HomeProto.Homes.getDefaultInstance()) return this;
        if (homeBuilder_ == null) {
          if (!other.home_.isEmpty()) {
            if (home_.isEmpty()) {
              home_ = other.home_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHomeIsMutable();
              home_.addAll(other.home_);
            }
            onChanged();
          }
        } else {
          if (!other.home_.isEmpty()) {
            if (homeBuilder_.isEmpty()) {
              homeBuilder_.dispose();
              homeBuilder_ = null;
              home_ = other.home_;
              bitField0_ = (bitField0_ & ~0x00000001);
              homeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHomeFieldBuilder() : null;
            } else {
              homeBuilder_.addAllMessages(other.home_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getHomeCount(); i++) {
          if (!getHome(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              HomeProto.Home.Builder subBuilder = HomeProto.Home.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addHome(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .model.Home home = 1;
      private java.util.List<HomeProto.Home> home_ =
        java.util.Collections.emptyList();
      private void ensureHomeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          home_ = new java.util.ArrayList<HomeProto.Home>(home_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          HomeProto.Home, HomeProto.Home.Builder, HomeProto.HomeOrBuilder> homeBuilder_;
      
      public java.util.List<HomeProto.Home> getHomeList() {
        if (homeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(home_);
        } else {
          return homeBuilder_.getMessageList();
        }
      }
      public int getHomeCount() {
        if (homeBuilder_ == null) {
          return home_.size();
        } else {
          return homeBuilder_.getCount();
        }
      }
      public HomeProto.Home getHome(int index) {
        if (homeBuilder_ == null) {
          return home_.get(index);
        } else {
          return homeBuilder_.getMessage(index);
        }
      }
      public Builder setHome(
          int index, HomeProto.Home value) {
        if (homeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHomeIsMutable();
          home_.set(index, value);
          onChanged();
        } else {
          homeBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setHome(
          int index, HomeProto.Home.Builder builderForValue) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          home_.set(index, builderForValue.build());
          onChanged();
        } else {
          homeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addHome(HomeProto.Home value) {
        if (homeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHomeIsMutable();
          home_.add(value);
          onChanged();
        } else {
          homeBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addHome(
          int index, HomeProto.Home value) {
        if (homeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHomeIsMutable();
          home_.add(index, value);
          onChanged();
        } else {
          homeBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addHome(
          HomeProto.Home.Builder builderForValue) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          home_.add(builderForValue.build());
          onChanged();
        } else {
          homeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addHome(
          int index, HomeProto.Home.Builder builderForValue) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          home_.add(index, builderForValue.build());
          onChanged();
        } else {
          homeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllHome(
          java.lang.Iterable<? extends HomeProto.Home> values) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          super.addAll(values, home_);
          onChanged();
        } else {
          homeBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearHome() {
        if (homeBuilder_ == null) {
          home_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          homeBuilder_.clear();
        }
        return this;
      }
      public Builder removeHome(int index) {
        if (homeBuilder_ == null) {
          ensureHomeIsMutable();
          home_.remove(index);
          onChanged();
        } else {
          homeBuilder_.remove(index);
        }
        return this;
      }
      public HomeProto.Home.Builder getHomeBuilder(
          int index) {
        return getHomeFieldBuilder().getBuilder(index);
      }
      public HomeProto.HomeOrBuilder getHomeOrBuilder(
          int index) {
        if (homeBuilder_ == null) {
          return home_.get(index);  } else {
          return homeBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends HomeProto.HomeOrBuilder>
           getHomeOrBuilderList() {
        if (homeBuilder_ != null) {
          return homeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(home_);
        }
      }
      public HomeProto.Home.Builder addHomeBuilder() {
        return getHomeFieldBuilder().addBuilder(
            HomeProto.Home.getDefaultInstance());
      }
      public HomeProto.Home.Builder addHomeBuilder(
          int index) {
        return getHomeFieldBuilder().addBuilder(
            index, HomeProto.Home.getDefaultInstance());
      }
      public java.util.List<HomeProto.Home.Builder>
           getHomeBuilderList() {
        return getHomeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          HomeProto.Home, HomeProto.Home.Builder, HomeProto.HomeOrBuilder>
          getHomeFieldBuilder() {
        if (homeBuilder_ == null) {
          homeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              HomeProto.Home, HomeProto.Home.Builder, HomeProto.HomeOrBuilder>(
                  home_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          home_ = null;
        }
        return homeBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:model.Homes)
    }
    
    static {
      defaultInstance = new Homes(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:model.Homes)
  }
  
  public interface HomeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required string rooms = 2;
    boolean hasRooms();
    String getRooms();
    
    // required int32 owner_id = 3;
    boolean hasOwnerId();
    int getOwnerId();
  }
  public static final class Home extends
      com.google.protobuf.GeneratedMessage
      implements HomeOrBuilder {
    // Use Home.newBuilder() to construct.
    private Home(Builder builder) {
      super(builder);
    }
    private Home(boolean noInit) {}
    
    private static final Home defaultInstance;
    public static Home getDefaultInstance() {
      return defaultInstance;
    }
    
    public Home getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HomeProto.internal_static_model_Home_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HomeProto.internal_static_model_Home_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required string rooms = 2;
    public static final int ROOMS_FIELD_NUMBER = 2;
    private java.lang.Object rooms_;
    public boolean hasRooms() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getRooms() {
      java.lang.Object ref = rooms_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          rooms_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRoomsBytes() {
      java.lang.Object ref = rooms_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        rooms_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 owner_id = 3;
    public static final int OWNER_ID_FIELD_NUMBER = 3;
    private int ownerId_;
    public boolean hasOwnerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getOwnerId() {
      return ownerId_;
    }
    
    private void initFields() {
      id_ = 0;
      rooms_ = "";
      ownerId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRooms()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOwnerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRoomsBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, ownerId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRoomsBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ownerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static HomeProto.Home parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static HomeProto.Home parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static HomeProto.Home parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static HomeProto.Home parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static HomeProto.Home parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static HomeProto.Home parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static HomeProto.Home parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static HomeProto.Home parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static HomeProto.Home parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static HomeProto.Home parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HomeProto.Home prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements HomeProto.HomeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HomeProto.internal_static_model_Home_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HomeProto.internal_static_model_Home_fieldAccessorTable;
      }
      
      // Construct using HomeProto.Home.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        rooms_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ownerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HomeProto.Home.getDescriptor();
      }
      
      public HomeProto.Home getDefaultInstanceForType() {
        return HomeProto.Home.getDefaultInstance();
      }
      
      public HomeProto.Home build() {
        HomeProto.Home result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private HomeProto.Home buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        HomeProto.Home result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public HomeProto.Home buildPartial() {
        HomeProto.Home result = new HomeProto.Home(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rooms_ = rooms_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ownerId_ = ownerId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HomeProto.Home) {
          return mergeFrom((HomeProto.Home)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(HomeProto.Home other) {
        if (other == HomeProto.Home.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasRooms()) {
          setRooms(other.getRooms());
        }
        if (other.hasOwnerId()) {
          setOwnerId(other.getOwnerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasRooms()) {
          
          return false;
        }
        if (!hasOwnerId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              rooms_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              ownerId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required string rooms = 2;
      private java.lang.Object rooms_ = "";
      public boolean hasRooms() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getRooms() {
        java.lang.Object ref = rooms_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          rooms_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRooms(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rooms_ = value;
        onChanged();
        return this;
      }
      public Builder clearRooms() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rooms_ = getDefaultInstance().getRooms();
        onChanged();
        return this;
      }
      void setRooms(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        rooms_ = value;
        onChanged();
      }
      
      // required int32 owner_id = 3;
      private int ownerId_ ;
      public boolean hasOwnerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getOwnerId() {
        return ownerId_;
      }
      public Builder setOwnerId(int value) {
        bitField0_ |= 0x00000004;
        ownerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearOwnerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ownerId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:model.Home)
    }
    
    static {
      defaultInstance = new Home(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:model.Home)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Homes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_Homes_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Home_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_model_Home_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nhome.proto\022\005model\"\"\n\005Homes\022\031\n\004home\030\001 \003" +
      "(\0132\013.model.Home\"3\n\004Home\022\n\n\002id\030\001 \002(\005\022\r\n\005r" +
      "ooms\030\002 \002(\t\022\020\n\010owner_id\030\003 \002(\005B5\n(vi.pract" +
      "ice.services.protobuf.home.modelB\tHomePr" +
      "oto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_model_Homes_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_model_Homes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_model_Homes_descriptor,
              new java.lang.String[] { "Home", },
              HomeProto.Homes.class,
              HomeProto.Homes.Builder.class);
          internal_static_model_Home_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_model_Home_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_model_Home_descriptor,
              new java.lang.String[] { "Id", "Rooms", "OwnerId", },
              HomeProto.Home.class,
              HomeProto.Home.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
